// Mocks generated by Mockito 5.4.6 from annotations
// in doffa/test/providers/metrics_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doffa/common/models.dart' as _i3;
import 'package:doffa/services/service.dart' as _i4;
import 'package:doffa/storage/storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStorage_0 extends _i1.SmartFake implements _i2.Storage {
  _FakeStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetrics_1 extends _i1.SmartFake implements _i3.Metrics {
  _FakeMetrics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIService extends _i1.Mock implements _i4.IService {
  MockIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Storage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeStorage_0(this, Invocation.getter(#storage)),
          )
          as _i2.Storage);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> toggleExpanded(_i2.StorageKeys? key) =>
      (super.noSuchMethod(
            Invocation.method(#toggleExpanded, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isExpanded(_i2.StorageKeys? key) =>
      (super.noSuchMethod(
            Invocation.method(#isExpanded, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setExpanded(_i2.StorageKeys? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setExpanded, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Metrics> getStart() =>
      (super.noSuchMethod(
            Invocation.method(#getStart, []),
            returnValue: _i5.Future<_i3.Metrics>.value(
              _FakeMetrics_1(this, Invocation.method(#getStart, [])),
            ),
          )
          as _i5.Future<_i3.Metrics>);

  @override
  _i5.Future<_i3.Metrics> setStart(_i3.Metrics? metrics) =>
      (super.noSuchMethod(
            Invocation.method(#setStart, [metrics]),
            returnValue: _i5.Future<_i3.Metrics>.value(
              _FakeMetrics_1(this, Invocation.method(#setStart, [metrics])),
            ),
          )
          as _i5.Future<_i3.Metrics>);

  @override
  _i5.Future<_i3.Metrics> getEnd() =>
      (super.noSuchMethod(
            Invocation.method(#getEnd, []),
            returnValue: _i5.Future<_i3.Metrics>.value(
              _FakeMetrics_1(this, Invocation.method(#getEnd, [])),
            ),
          )
          as _i5.Future<_i3.Metrics>);

  @override
  _i5.Future<_i3.Metrics> setEnd(_i3.Metrics? metrics) =>
      (super.noSuchMethod(
            Invocation.method(#setEnd, [metrics]),
            returnValue: _i5.Future<_i3.Metrics>.value(
              _FakeMetrics_1(this, Invocation.method(#setEnd, [metrics])),
            ),
          )
          as _i5.Future<_i3.Metrics>);
}

/// A class which mocks [Storage].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorage extends _i1.Mock implements _i2.Storage {
  MockStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> write(_i2.StorageKeys? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> writeBool(_i2.StorageKeys? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#writeBool, [key, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> read(_i2.StorageKeys? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#read, [key])),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<bool> readBool(_i2.StorageKeys? key) =>
      (super.noSuchMethod(
            Invocation.method(#readBool, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> delete(_i2.StorageKeys? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
