name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch that triggers the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/web  # Directory containing your Flutter web build output
          publish_branch: gh-pages  # The branch to deploy to (usually gh-pages)
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github  # Exclude the .github folder from being published

